### ISSUE TITLE
Dont start :/

### ISSUE THREAD

**Issue by elek01** [WaterTheDev/Vibez-Discord-Selfbot#4]
When i start the main.py it starts but dies instantly.

**Comment by qwerm14** [comment]
You need to use the .exe file

**Comment by qwerm14** [comment]
same

**Comment by dromzeh** [comment]
> 
> 
> When i start the main.py it starts but dies instantly.

open it within cmd prompt / terminal instead of double clicking on the file to run it, that way the error should show before immediately closing

**Comment by WaterTheDev** [comment]
Sorry for the late response.
Please install the requirements in the requirements.txt file.
Do "pip install -r requirements.txt" in your terminal and retry
This issue will now be closed.
