### ISSUE TITLE
main.py file problem

### ISSUE THREAD

**Issue by qwerm14** [WaterTheDev/Vibez-Discord-Selfbot#6]
the main.py file closes right when i open it, my anti virus is off and it should run?

**Comment by dromzeh** [comment]
how are you opening the file? make sure you edited the config with the correct token and make sure you're opening the file through a terminal / command prompt e.g `py main.py` which will normally output the error instead of closing immediately if you are just running by double clicking on the file.

**Comment by WaterTheDev** [comment]
Sorry for the late response.
Please install the requirements in the requirements.txt file.
Do "pip install -r requirements.txt" in your terminal and retry
This issue will now be closed.
