### ISSUE TITLE
images and time stamp

### ISSUE THREAD

**Issue by thizsam** [WaterTheDev/Vibez-Discord-Selfbot#9]
the button arent coming up as u shown, and cant we ad images and timestamps ?
![Capture](https://user-images.githubusercontent.com/82769814/125164027-b360f600-e1ad-11eb-9988-523009244ef7.PNG)

**Comment by 6af** [comment]
You can make a script for that in node.js

**Comment by WaterTheDev** [comment]
Discord disallows any link that isn't YOUTUBE.COM or TWITCH.TV
Please edit the link in the config.json

This issue will now be closed.
